#!/command/with-contenv bash
# shellcheck shell=bash

PUID=${PUID:-901}
PGID=${PGID:-901}
TZ=${TZ:-UTC}

groupmod -o -g "$PGID" disty
usermod -o -u "$PUID" disty

echo "
-------------------------------------"
echo "
UID/GID/TZ Information:
-------------------------------------"
echo "
User uid :    $(id -u disty)
User gid :    $(id -g disty)
Timezone :    $TZ
-------------------------------------"

chown disty:disty /app
chown disty:disty /config
chown disty:disty /defaults